
###
GET http://localhost:5168/games


###
GET http://localhost:5168/games/c5948789-4a90-4058-af21-62f986445828


###
POST http://localhost:5168/games
Content-Type: application/json

{
  "name": "Hhshhj",
  "description": "Hjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhj",
  "genreId": "f7f5c0c9-b5c7-4f0d-a5c5-f7f5c0c9b5c8",
  "price": 30.00,
  "releaseDate": "2025-09-26"
}


###
PUT http://localhost:5168/games/c5948789-4a90-4058-af21-62f986445828
Content-Type: application/json

{
  "name": "GTA V",
  "description": "Hjhjhjhjhjhjhjhjhjhjhjh dsf",
  "genreId": "f7f5c0c9-b5c7-4f0d-a5c5-f7f5c0c9b5c8",
  "price": 30.00,
  "releaseDate": "2025-09-26"
}

###
DELETE http://localhost:5168/games/c5948789-4a90-4058-af21-62f986445828


###
GET http://localhost:5168/genres