
### 
GET http://localhost:5096/games

###
GET http://localhost:5096/games/e4e3519d-6459-4c22-b60e-d1ba548ae1f8


###
POST http://localhost:5096/games
Content-Type: application/json

{
  "name": "New Game",
  "genreId": "6949CE07-4A1D-49EA-B59F-66CC9F8E474B",
  "releaseDate": "2024-07-01",
  "price": 320.00,
  "description": "New Game Description"
}


###
PUT http://localhost:5096/games/F4EE4693-505D-41CC-BB4F-1D9A48E256BB
Content-Type: application/json

{
  "name": "Updated Game Name",
  "genreId": "BF060BE4-BE8F-450D-A048-6B4548C358DB",
  "releaseDate": "2024-08-01",
  "price": 150.00,
  "description": "Updated Game Description"
}

###
DELETE http://localhost:5096/games/89F5C3D7-E5FC-4C4E-A2A7-05AE893C4E7D

###
GET http://localhost:5096/genres