
###
GET http://localhost:5666/games

###
GET http://localhost:5666/games/11663ebc-f65a-4c86-bb64-47d37d4b8d7b

###
POST http://localhost:5666/games
Content-Type: application/json

{
  "Name": "New One",
  "Description": "New Game Description",
  "GenreId": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
  "Price": 100.99,
  "ReleaseDate": "2021-01-01"
}

###
PUT http://localhost:5666/games/11663ebc-f65a-4c86-bb64-47d37d4b8d7b
Content-Type: application/json

{
  "Name": "Update",
  "GenreId": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
  "Price": 160.99,
  "ReleaseDate": "2025-11-11",
  "Description": "Update Description"
}

### 
DELETE http://localhost:5666/games/11663ebc-f65a-4c86-bb64-47d37d4b8d7b


###
GET http://localhost:5666/genres/